[package]
edition = "2024"
name = "naming"
version = "0.1.0"
authors = ["Michael Sch√∂ttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
syscall = { path = "../syscall" }
terminal = { path = "../terminal" }

# External depencies
num_enum = { version = "0.7", default-features = false }
bitflags = "1.0"
