[package]
edition = "2024"
name = "syscall"
version = "0.1.0"
authors = ["Michael Sch√∂ttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
# External depencies
num_enum = { version = "0.7", default-features = false }
bitflags = "1.0"
