[package]
edition = "2024"
name = "terminal"
version = "0.1.0"
authors = ["Michael Sch√∂ttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[dependencies]
# Local dependencies
syscall = { path = "../syscall" }

# External dependencies
spin = "0.9.8"
num_enum = { version = "0.7", default-features = false }