[package]
edition = "2024"
name = "date"
version = "0.1.0"
authors = ["Michael SchÃ¶ttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[lib]
crate-type = ["staticlib"]
path = "src/date.rs"
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
runtime = { path = "../../library/runtime" }
terminal = { path = "../../library/terminal" }
time = { path = "../../library/time" }