[package]
edition = "2024"
name = "time"
version = "0.1.0"
authors = ["Michael Sch√∂ttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>, Sandro Jose Leal Miudo"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
syscall = { path = "../syscall" }

# External dependencies
chrono = { version = "0.4.34", default-features = false, features = ["alloc"] }